# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_change-default-python-interpreter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enable_roe_build',
            field=models.BooleanField(default=False, help_text='Publish your documentation to River of Ebooks with each build.', verbose_name='Enable River of Ebooks publishing'),
        ),
    ]
