# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20190211_0918'),
        ('projects', '0039_update-doctype-helptext'),
    ]

    operations = [
    ]
