# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_index-repo-field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_roe_build',
            field=models.BooleanField(default=False, help_text='Publish your documentation to River of Ebooks with each build', verbose_name='Enable River of Ebooks publishing'),
        ),
    ]
